### PR TITLE
Monoid example with marker structs

### PR DESCRIPTION
**Pull request by yannbolliger**
This is an extension to the current Monoid example of type classes. It shows that trait bounds on functions don't work yet.

### CODE REVIEW

**Comment by romac** [comment]
@yannbolliger This should now work right?

**Comment by yannbolliger** [comment]
> This should now work right?

It should, but verification fails. I'll look into why.

**Comment by yannbolliger** [comment]
What's missing for this to work is the correct handling of:
```rust
pub trait Monoid<O: Op> {}
```

Currently, this is translated as:
```scala
@abstract
@sealed
sealed abstract class Monoid$0[Monoid$0, O$0] extends Op$0[O$0]
```
which is of course wrong.

**Comment by yannbolliger** [comment]
Closing this as an archival action.

**Pull request closed without merging**
